import os
import xml.etree.ElementTree as ET
from collections import defaultdict

xml_files = [
    "ree_parsewhole_corpus/out_inNsDefault_c14nDefault.xml",
    "./cpython/PC/classicAppCompat.can.xml",
    "./cpython/Lib/test/xmltestdata/simple-ns.xml",
    "./cpython/Lib/test/xmltestdata/simple.xml",
    "./cpython/Lib/test/xmltestdata/c14n-20/out_inC14N4_c14nTrim.xml",
    "./cpython/Lib/test/xmltestdata/c14n-20/out_inNsSuperfluous_c14nPrefix.xml",
    "./cpython/Lib/test/xmltestdata/c14n-20/inC14N2.xml",
    "./cpython/Lib/test/xmltestdata/c14n-20/out_inC14N2_c14nTrim.xml",
    "./cpython/Lib/test/xmltestdata/c14n-20/out_inC14N3_c14nTrim.xml",
    "./cpython/Lib/test/xmltestdata/c14n-20/c14nPrefixQnameXpathElem.xml",
    "./cpython/Lib/test/xmltestdata/c14n-20/inNsPushdown.xml",
    "./cpython/Lib/test/xmltestdata/c14n-20/out_inC14N3_c14nDefault.xml",
    "./cpython/Lib/test/xmltestdata/c14n-20/c14nQname.xml",
    "./cpython/Lib/test/xmltestdata/c14n-20/out_inNsPushdown_c14nPrefix.xml",
    "./cpython/Lib/test/xmltestdata/c14n-20/out_inNsPushdown_c14nDefault.xml",
    "./cpython/Lib/test/xmltestdata/c14n-20/c14nComment.xml",
    "./cpython/Lib/test/xmltestdata/c14n-20/out_inNsSuperfluous_c14nDefault.xml",
    "./cpython/Lib/test/xmltestdata/c14n-20/inNsDefault.xml",
    "./cpython/Lib/test/xmltestdata/c14n-20/out_inC14N1_c14nComment.xml",
    "./cpython/Lib/test/xmltestdata/c14n-20/out_inC14N5_c14nDefault.xml",
    "./cpython/Lib/test/xmltestdata/c14n-20/out_inNsSort_c14nPrefix.xml",
    "./cpython/Lib/test/xmltestdata/c14n-20/c14nQnameXpathElem.xml",
    "./cpython/Lib/test/xmltestdata/c14n-20/inNsRedecl.xml",
    "./cpython/Lib/test/xmltestdata/c14n-20/out_inNsRedecl_c14nDefault.xml",
    "./cpython/Lib/test/xmltestdata/c14n-20/c14nQnameElem.xml",
    "./cpython/Lib/test/xmltestdata/c14n-20/out_inC14N6_c14nDefault.xml",
    "./cpython/Lib/test/xmltestdata/c14n-20/out_inNsContent_c14nQnameXpathElem.xml",
    "./cpython/Lib/test/xmltestdata/c14n-20/out_inNsXml_c14nPrefix.xml",
    "./cpython/Lib/test/xmltestdata/c14n-20/inC14N4.xml",
    "./cpython/Lib/test/xmltestdata/c14n-20/c14nPrefix.xml",
    "./cpython/Lib/test/xmltestdata/c14n-20/out_inC14N1_c14nDefault.xml",
    "./cpython/Lib/test/xmltestdata/c14n-20/out_inC14N2_c14nDefault.xml",
    "./cpython/Lib/test/xmltestdata/c14n-20/inNsSuperfluous.xml",
    "./cpython/Lib/test/xmltestdata/c14n-20/c14nPrefixQname.xml",
    "./cpython/Lib/test/xmltestdata/c14n-20/out_inNsDefault_c14nPrefix.xml",
    "./cpython/Lib/test/xmltestdata/c14n-20/out_inNsContent_c14nQnameElem.xml",
    "./cpython/Lib/test/xmltestdata/c14n-20/out_inNsXml_c14nDefault.xml",
    "./cpython/Lib/test/xmltestdata/c14n-20/inC14N3.xml",
    "./cpython/Lib/test/xmltestdata/c14n-20/inNsXml.xml",
    "./cpython/Lib