import os
import re

def count_classes_in_file(file_path):
    with open(file_path, 'r') as file:
        content = file.read()
    class_pattern = re.compile(r'^class\s+\w+\s*:', re.MULTILINE)
    return len(class_pattern.findall(content))

def main():
    python_files = [
        'scripts/divmod_threshold.py',
        './cpython/Tools/scripts/sortperf.py',
        './cpython/Tools/scripts/long_conv_tables.py',
        './cpython/Tools/scripts/var_access_benchmark.py',
        './cpython/Tools/scripts/combinerefs.py',
        './cpython/Tools/scripts/summarize_stats.py',
        './cpython/Tools/check-c-api-docs/main.py',
        './cpython/Tools/build/smelly.py',
        './cpython/Tools/build/consts_getter.py',
        './cpython/Tools/build/generate_global_objects.py',
        './cpython/Tools/build/generate_slots.py',
        './cpython/Tools/build/freeze_modules.py',
        './cpython/Tools/build/parse_html5_entities.py',
        './cpython/Tools/build/generate_token.py',
        './cpython/Tools/build/umarshal.py',
        './cpython/Tools/build/generate_stdlib_module_names.py',
        './cpython/Tools/build/stable_abi.py',
        './cpython/Tools/build/generate_sre_constants.py',
        './cpython/Tools/build/generate_build_details.py',
        './cpython/Tools/build/update_file.py',
        './cpython/Tools/build/deepfreeze.py',
        './cpython/Tools/build/compute-changes.py',
        './cpython/Tools/build/check_warnings.py',
        './cpython/Tools/build/generate_levenshtein_examples.py',
        './cpython/Tools/build/check_extension_modules.py',
        './cpython/Tools/build/generate_re_casefix.py',
        './cpython/Tools/build/verify_ensurepip_wheels.py',
        './cpython/Tools/build/generate_sbom.py',
        './cpython/Tools/jit/_llvm.py',
        './cpython/Tools/jit/_dwarf.py',
        './cpython/Tools/jit/_stencils.py',
        './cpython/Tools/jit/build.py',
        './cpython/Tools/jit/example_trace_dump.py',
        './cpython/Tools/jit/_optimizers.py',
        './cpython/Tools/jit/_writer.py',
        './cpython/Tools/jit/_schema.py',
        './cpython/Tools/jit/_targets.py',
        './cpython/Tools/wasm/emscripten/__main__.py',
        './cpython/Tools/wasm/wasi.py',
        './cpython/Tools/wasm/wasi/__main__.py',
        './cpython/Tools/unicode/dawg.py',
        './cpython/Tools/unicode/comparecodecs.py',
        './cpython/Tools/unicode/listcodecs.py',
        './cpython/Tools/unicode/genmap_korean.py',
        './cpython/Tools/unicode/genwincodec.py',
        './cpython/Tools/unicode/genmap_support.py',
        './cpython/Tools/unicode/makeunicodedata.py',
        './cpython/Tools/unicode/genmap_japanese.py',
        './cpython/Tools/unicode/gencodec.py',
        './cpython/Tools/unicode/genmap_schinese.py',
        './cpython/Tools/unicode/mkstringprep.py',
        './cpython/Tools/unicode/genmap_tchinese.py',
        './cpython/Tools/unicode/gencjkcodecs.py',
        './cpython/Tools/patchcheck/patchcheck.py',
        './cpython/Tools/patchcheck/reindent.py',
        './cpython/Tools/patchcheck/untabify.py',
        './cpython/Tools/importbench/importbench.py',
        './cpython/Parser/asdl_c.py',
        './cpython/Parser/asdl.py',
        './cpython/Platforms/Apple/testbed/__main__.py',
        './cpython/Platforms/Apple/__main__.py',
        './cpython/Platforms/emscripten/prepare_external_wasm.py',
        './cpython/Platforms/emscripten/web_example/server.py',
        './cpython/Platforms/emscripten/__main__.py',
        './cpython/Platforms/emscripten/wasm_assets.py',
        './cpython/Platforms/Android/__main__.py',
        './cpython/Platforms/WASI/_build.py',
        './cpython/Platforms/WASI/__main__.py',
        './requests/tests/test_adapters.py',
        './requests/tests/test_testserver.py',
        './requests/tests/test_structures.py',
        './requests/tests/__init__.py',
        './requests/tests/test_help.py',
        './requests/tests/test_requests.py',
        './requests/tests/compat