import requests
import json

# Define the list of cities and their corresponding continent
cities = {
    "London": "Europe",
    "New York City": "North America",
    "Tokyo": "Asia",
    "Sydney": "Australia",
    "Cairo": "Africa",
    "Rio de Janeiro": "South America",
    "Moscow": "Europe",
    "Beijing": "Asia",
    "Mumbai": "Asia",
    "Delhi": "Asia",
    "Sao Paulo": "South America",
    "Toronto": "North America",
    "Berlin": "Europe",
    "Paris": "Europe",
    "Rome": "Europe",
    "Madrid": "Europe",
    "Washington D.C.": "North America",
    "Seoul": "Asia",
    "Beijing": "Asia",
    "Jakarta": "Asia",
    "Manila": "Asia",
    "Lagos": "Africa",
    "Johannesburg": "Africa",
    "Cape Town": "Africa",
    "Nairobi": "Africa",
    "Buenos Aires": "South America",
    "Rio de Janeiro": "South America",
    "Santiago": "South America",
    "Mexico City": "North America",
    "Chicago": "North America",
    "Los Angeles": "North America",
    "Miami": "North America",
    "Houston": "North America",
    "Phoenix": "North America",
    "San Francisco": "North America",
    "Seattle": "North America",
    "Toronto": "North America",
    "Vancouver": "North America",
    "Montreal": "North America",
    "Sydney": "Australia",
    "Melbourne": "Australia",
    "Brisbane": "Australia",
    "Perth": "Australia",
    "Adelaide": "Australia",
    "Auckland": "Australia",
    "Wellington": "Australia",
    "Beijing": "Asia",
    "Shanghai": "Asia",
    "Guangzhou": "Asia",
    "Shenzhen": "Asia",
    "Delhi": "Asia",
    "Mumbai": "Asia",
    "Kolkata": "Asia",
    "Bangalore": "Asia",
    "Chennai": "Asia",
    "Hyderabad": "Asia",
    "Ahmedabad": "Asia",
    "Beijing": "Asia",
    "Shanghai": "Asia",
    "Guangzhou": "Asia",
    "Shenzhen": "Asia",
    "Lagos": "Africa",
    "Cairo": "Africa",
    "Johannesburg": "Africa",
    "Cape Town": "Africa",
    "Nairobi": "Africa",
    "Sao Paulo": "South America",
    "Buenos Aires": "South America",
    "Rio de Janeiro": "South America",
    "Santiago": "South America",
    "Mexico City": "North America",
    "Chicago": "North America",
    "Los Angeles": "North America",
    "Miami": "North America",
    "Houston": "North America",
    "Phoenix": "North America",
    "San Francisco": "North America",
    "Seattle": "North America",
    "Toronto": "North America",
    "Vancouver": "North America",
    "Montreal": "North America",
    "Sydney": "Australia",
    "Melbourne": "Australia",
    "Brisbane": "Australia",
    "Perth": "Australia",
    "Adelaide": "Australia",
    "Auckland": "Australia",
    "Wellington": "Australia",
    "Beijing": "Asia",
    "Shanghai": "Asia",
    "Guangzhou": "Asia",
    "Shenzhen": "Asia",
    "Delhi": "Asia",
    "Mumbai": "Asia",
    "Kolkata": "Asia",
    "Bangalore": "Asia",
    "Chennai": "Asia",
    "Hyderabad": "Asia",
    "Ahmedabad": "Asia",
}

# Create an empty dictionary to store the weather data
weather_data = {}

# Iterate over the cities and retrieve the weather data
for city, continent in cities.items():
    # Construct the API endpoint for the current weather
    api_endpoint = f"https://api.openweathermap.org/data/2.5/weather?q={city}&appid=YOUR_API_KEY&units=metric"

    # Send a GET request to the API endpoint
    response = requests.get(api_endpoint)

    # Check for successful response
    if response.status_code == 200:
        # Parse the