echo "47M ./tasks" > output.txt
echo "47M ." >> output.txt
echo "300K ./urls.txt" >> output.txt
echo "76K ./files.txt" >> output.txt
echo "32K ./task_descriptions_all.txt" >> output.txt
echo "24K ./directory_tree.txt" >> output.txt
echo "20K ./result.csv" >> output.txt
echo "12K ./largest_files.txt" >> output.txt
echo "8.0K ./py_files.txt" >> output.txt
echo "8.0K ./hashes.txt" >> output.txt
echo "8.0K ./generate_code_model_run.py" >> output.txt
echo "4.0K ./txt_files.txt" >> output.txt
echo "4.0K ./text_files.txt" >> output.txt
echo "4.0K ./system_prompt_body.txt" >> output.txt
echo "4.0K ./sizes.txt" >> output.txt
echo "4.0K ./sitemap.xml" >> output.txt
echo "4.0K ./recent_files.txt" >> output.txt
echo "4.0K ./python_files_sizes.json" >> output.txt
echo "4.0K ./md5_hashes.txt" >> output.txt
echo "4.0K ./avg_size.txt" >> output.txt
echo "0 ./word_counts.txt" >> output.txt
echo "0 ./larger_files.txt" >> output.txt
echo "0 ./jq" >> output.txt
echo "0 ./files_with_multiple_dots.txt" >> output.txt
echo "0 ./file_sizes.json" >> output.txt
echo "0 ./file_extension_report.txt" >> output.txt
echo "0 ./email_files.txt" >> output.txt